# -----------------------------------------------------
# Window rules
# -----------------------------------------------------
# hyprctl clinets

windowrule = tile, title:^(Microsoft-edge)$
windowrule = tile, title:^(Brave-browser)$
windowrule = tile, title:^(Chromium)$
windowrule = float, title:^(pavucontrol)$
windowrule = float, title:^(blueman-manager)$
windowrule = float, title:^(nm-connection-editor)$
windowrule = float, title:^(qalculate-gtk)$

# Browser Picture in Picture
windowrule = float, title:^(Picture in picture)$
windowrule = pin, title:^(Picture in picture)$
windowrule = move 69.5% 4%, title:^(Picture in picture)$
windowrule = opacity 1.1, title:^(Picture in picture)$

# Nextcloud Settings
windowrule = float, title:^(Nextcloud Settings)$
windowrule = center, title:^(Nextcloud Settings)$
windowrule = size 640 630, title:^(Nextcloud Settings)$

# Remove Opacity for youtube
windowrule = opacity 1.1, title:.*YouTube.*

# Remove Opacity for floating windows
windowrule = opacity 1.1, floating:1

# idleinhibit
windowrule = idleinhibit fullscreen,class:([window]) # Available modes: none, always, focus, fullscreen
