return {

  require("luasnip").snippet({ trig = "shabang", dscr = "Drop in shabang" }, { t("#! /usr/bin/env bash") }),

  require("luasnip").snippet({ trig = "pipefail" }, { t("set -euo pipefail") }),

  require("luasnip").snippet({ trig = "colors", dscr = "Add colored output" }, {
    t({
      "# -----------------------------",
      "# Colors",
      "# -----------------------------",
      "if [[ -t 1 ]]; then",
      "  RED=$'\\e[31m'",
      "  GREEN=$'\\e[32m'",
      "  YELLOW=$'\\e[33m'",
      "  BLUE=$'\\e[34m'",
      "  BOLD=$'\\e[1m'",
      "  RESET=$'\\e[0m'",
      "else",
      '  RED=""',
      '  GREEN=""',
      '  YELLOW=""',
      '  BLUE=""',
      '  BOLD=""',
      '  RESET=""',
      "fi",
      "",
      'info() { echo "${BLUE}${BOLD}==>${RESET} $*"; }',
      'success() { echo "${GREEN}${BOLD}✔${RESET}  $*"; }',
      'warn() { echo "${YELLOW}${BOLD}⚠${RESET}  $*"; }',
      'error() { echo "${RED}${BOLD}✖${RESET}  $*" >&2; }',
      "",
    }),
  }),

  require("luasnip").snippet({ trig = "basicsetup", dscr = "Add shabang, pipefail, and colored output" }, {
    t({
      "#!/usr/bin/env bash",
      "set -euo pipefail",
      "# -----------------------------",
      "# Colors",
      "# -----------------------------",
      "if [[ -t 1 ]]; then",
      "  RED=$'\\e[31m'",
      "  GREEN=$'\\e[32m'",
      "  YELLOW=$'\\e[33m'",
      "  BLUE=$'\\e[34m'",
      "  BOLD=$'\\e[1m'",
      "  RESET=$'\\e[0m'",
      "else",
      '  RED=""',
      '  GREEN=""',
      '  YELLOW=""',
      '  BLUE=""',
      '  BOLD=""',
      '  RESET=""',
      "fi",
      "",
      'info() { echo "${BLUE}${BOLD}==>${RESET} $*"; }',
      'success() { echo "${GREEN}${BOLD}✔${RESET}  $*"; }',
      'warn() { echo "${YELLOW}${BOLD}⚠${RESET}  $*"; }',
      'error() { echo "${RED}${BOLD}✖${RESET}  $*" >&2; }',
      "",
    }),
  }),
}
