
exec-once = [workspace 1 silent] brave
exec-once = [workspace 2 silent] kitty

exec-once = waybar
exec-once = swaync
exec-once = awww-daemon
exec-once = hypridle
exec-once = nextcloud
# exec-once = hyprsunset
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Polkit agent (choose the one you installed)
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# Secret service (autostarts via PAM; see below). Fallback autostart:
exec-once = /usr/bin/gnome-keyring-daemon --start --components=secrets,pkcs11,ssh
