# https://wiki.hypr.land/Configuring/Keywords/
# example binds, see:
# https://wiki.hypr.land/Configuring/Binds/

# Grouping of binds for easier management
#  $d=[Group Name|Subgroup Name1|Subgroup Name2|...]
# '$d' is a variable that is used to group binds together (or use another variable)
# This is only for organization purposes and is not a defined hyprland variable
# What we did here is to modify the Description of the binds to include the group name
# The $d will be parsed as a separate key to be use for a GUI or something pretty
# [Main|Subgroup1|Subgroup2|...]
# Main - The main groupname
# Subgroup1.. - The subgroup names can be use to avoid repeating the same description

#* Variables 
$mainMod = Super # super / meta / windows key

#* Screenshot variables 
$shotDir = /home/zaiquiri/Photos/Screenshots/
env = HYPRSHOT_DIR,$shotDir
exec-once = mkdir -p $shotDir

# Assign apps
$TERMINAL = kitty
$MESSENGER = signal-desktop
$MESSENGER2 = whatsapp-linux-desktop
$EXPLORER = nautilus
$BROWSER = brave
$LAUNCHER_MENU  = $HOME/.config/rofi/scripts/launcher.sh
$APPS_MENU = $HOME/.config/rofi/applets/bin/apps.sh
$SCREENSHOT_MENU = $HOME/.config/rofi/applets/bin/screenshot.sh
$POWER_MENU = $HOME/.config/rofi/scripts/powermenu.sh
$THEME_PICKER = $HOME/.config/rofi/scripts/pick-picker.sh


