foreground              #090909
background              #BBC7CF
selection_foreground    #BBC7CF
selection_background    #090909
cursor                  #192C39
cursor_text_color       #FFFFFF

active_tab_foreground     #BBC7CF
active_tab_background     #4D798B
inactive_tab_foreground   #4D798B
inactive_tab_background   #BBC7CF

# black
color0      #294152
color8      #57798F

# red
color1      #CCEAFF
color9      #AAD3F0

# green
color2      #FFDECC
color10     #F0C3AA

# yellow
color3      #CCF0FF
color11     #AADCF0

# blue
color4      #9AC7E6
color12     #9AC7E6

# magenta
color5      #E6B49A
color13     #E6B49A

# cyan
color6      #9AD0E6
color14     #9AD0E6

# white
color7      #CCEAFF
color15     #AAD3F0
