# ~/.config/hypr/hyprsunset.conf

# Upper limit used for gamma scaling internally
max-gamma = 150

# Day profile: no change
profile {
  time = 07:30
  identity = true
}

# Evening: slightly warm
profile {
  time = 20:00
  temperature = 5000
  gamma = 0.95
}

# Night: warm + a touch dimmer
profile {
  time = 22:30
  temperature = 3800
  gamma = 0.85
}
