# Hyprland main config
# Docs: https://wiki.hypr.land/Configuring/

# -----------------------------------------------------------------------------
# Includes
# -----------------------------------------------------------------------------

# Monitors: https://wiki.hypr.land/Configuring/Monitors/
# The I just want to set the monitors my self config
# source = ~/.config/hypr/hyprconfigs/monitors.conf
# The I want to use the tui config (don't edit it manually)
source = ~/.config/hypr/monitors.conf

# Autostart 
source = ~/.config/hypr/hyprconfigs/autostart.conf

# Look & feel
source = ~/.config/hypr/hyprconfigs/look_and_feel.conf

# Input: https://wiki.hypr.land/Configuring/Variables/#input
source = ~/.config/hypr/hyprconfigs/input.conf

# Keybinds: https://wiki.hypr.land/Configuring/Binds/
source = ~/.config/hypr/hyprconfigs/keybinds.conf

# Window/workspace rules:
# - Window rules: https://wiki.hypr.land/Configuring/Window-Rules/
# - Workspace rules: https://wiki.hypr.land/Configuring/Workspace-Rules/
source = ~/.config/hypr/hyprconfigs/window_rules.conf

# -----------------------------------------------------------------------------
# Environment
# -----------------------------------------------------------------------------
# Env vars: https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
