
bind = $super, D, exec, $menu
bind = $super SHIFT, D, exec, $fullmenu
bind = $super, I, exec, $browser
bind = $super, Return, exec, $term
bind = $super SHIFT, Return, exec, $term -e tmux
bind = $super, T, exec, $files
bind = $super, E, exec, $email
# bind = $super, M, exec, $messenger
bind = $super, S, exec, spotify
bind = $super, R, exec, rofi-theme-selector
bind = $super, V, exec, pavucontrol
bind = $super, P, exec, powermenu

bind = , mouse:275, exec, ../scripts/launchjellyfin


