# Setting variables
$super = SUPER
$localBin = $HOME/.local/bin
$scriptsDir = $HOME/.config/hypr/scripts
$hyprDir = $HOME/.config/hypr
$menu = $scriptsDir/menu
$fullmenu = $scriptsDir/fullmenu
$volume = $scriptsDir/volume

$brightness = $scriptsDir/brightness
$screenshot = $scriptsDir/screenshot
$lock = $scriptsDir/lockscreen
$colorpicker = $scriptsDir/colorpicker
$wofi_beats = $scriptsDir/wofi-beats
$files = thunar
$browser = brave-browser-beta
$editor = alacritty -e lvim
$term = kitty
$email = thunderbird
$messenger = signal-desktop
