# ~/.config/zsh/.zshrc
#
# This is the main entry point for interactive zsh sessions.
# Keep this file focused on:
#   1. startup-sensitive initialization,
#   2. plugin manager setup,
#   3. loading modular config files,
#   4. loading the prompt config.
#
# Day-to-day shell settings such as aliases, functions, history, keybinds,
# completions, and tool integrations should live in ~/.config/zsh/zshrc/.

# -----------------------------------------------------
# Powerlevel10k instant prompt
# -----------------------------------------------------
# This should stay near the top of the file.
#
# Any code that may require user input (password prompts, confirmations, etc.)
# must go above this block. Everything else should go below it.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# -----------------------------------------------------
# Homebrew environment
# -----------------------------------------------------
# On macOS, Homebrew can export PATH and other environment variables needed
# for installed tools. This makes brew-installed programs available in zsh.
#
# If you later move login-only environment setup into ~/.config/zsh/.zprofile,
# this section can be moved there.
if [[ -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# -----------------------------------------------------
# Zinit plugin manager
# -----------------------------------------------------
# Store Zinit under the XDG data directory so plugin files live under ~/.local/share
# instead of cluttering the home directory.
ZINIT_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/zinit/zinit.git"

# Install Zinit automatically if it has not been cloned yet.
if [[ ! -d "$ZINIT_HOME" ]]; then
  mkdir -p "$(dirname "$ZINIT_HOME")"
  git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Load the plugin manager.
source "$ZINIT_HOME/zinit.zsh"

# -----------------------------------------------------
# Prompt theme
# -----------------------------------------------------
# Load the Powerlevel10k theme through Zinit.
zinit ice depth=1
zinit light romkatv/powerlevel10k

# -----------------------------------------------------
# Core plugins
# -----------------------------------------------------
# These plugins provide:
# - syntax highlighting while typing commands,
# - extra completion definitions,
# - fish-style command suggestions,
# - fzf-based completion menus.
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab

# -----------------------------------------------------
# Oh My Zsh snippets
# -----------------------------------------------------
# These snippets load useful helper scripts and plugin behavior without
# installing the full Oh My Zsh framework.
zinit snippet OMZL::git.zsh
zinit snippet OMZP::git
zinit snippet OMZP::sudo
zinit snippet OMZP::archlinux
zinit snippet OMZP::command-not-found
zinit snippet OMZP::eza
zinit snippet OMZP::zoxide

# -----------------------------------------------------
# Completion system
# -----------------------------------------------------
# Initialize zsh's completion system after loading completion-related plugins.
autoload -Uz compinit
compinit

# Let Zinit replay any cached completions provided by plugins.
zinit cdreplay -q

# -----------------------------------------------------
# Load modular interactive configuration
# -----------------------------------------------------
# Source each *.zsh file in ~/.config/zsh/zshrc/.
#
# This is where aliases, functions, history settings, keybinds, completion
# styling, and shell integrations should live.
if [[ -d "$ZDOTDIR/zshrc.d" ]]; then
  for f in "$ZDOTDIR"/zshrc.d/*.zsh(N); do
    source "$f"
  done
else
  echo "Warning: Could not find $ZDOTDIR/zshrc"
fi

# -----------------------------------------------------
# Powerlevel10k personal prompt config
# -----------------------------------------------------
# This file is generated by `p10k configure` and contains your prompt settings.
[[ -f "$ZDOTDIR/.p10k.zsh" ]] && source "$ZDOTDIR/.p10k.zsh"

# bun completions
[ -s "/home/zaiquiri/.bun/_bun" ] && source "/home/zaiquiri/.bun/_bun"
