#!/bin/bash

# hyprctl dispatch focusmonitor HDMI-A-6
# brave --app=http://192.168.1.11:8096/
# hyprctl dispatch workspace 1

hyprctl dispatch exec brave
sleep .5
hyprctl dispatch movetoworkspacesilent 1

sleep .5
hyprctl dispatch exec "kitty --hold sh -c 'zellij --layout=work_layout'"
sleep .5
hyprctl dispatch movetoworkspacesilent 2

sleep .5
hyprctl dispatch exec morgen
sleep .5
hyprctl dispatch movetoworkspacesilent 3

sleep .5
hyprctl dispatch exec /home/zaiquiri/WebApps/outlook-linux-x64/outlook
sleep .5
hyprctl dispatch movetoworkspacesilent 3

sleep .5
hyprctl dispatch exec /home/zaiquiri/WebApps/trello-linux-x64/trello
sleep .5
hyprctl dispatch movetoworkspacesilent 4
