#!/bin/bash

#wallpaper fetcher and wallpaper rotator
#type "var" in a terminal to change settings - example
#variety &

SCRIPTSDIR=$HOME/.config/hypr/scripts

# polkit agent
if ! pidof polkit-gnome-authentication-agent-1 >/dev/null; then
  /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
fi

# Apply themes
${SCRIPTSDIR}/gtkthemes &

# Lauch notification daemon (mako)
${SCRIPTSDIR}/notifications &

# Xauthority
${SCRIPTSDIR}/xauthority &

dex $HOME/.config/autostart/arcolinux-welcome-app.desktop &

#insync start &
#dropbox &
#telegram-desktop &
#discord &
nm-applet --indicator
