preload = /home/zaiquiri/Pictures/Wallpapers/Favorites/japanese_style_ocean_waves_at_sunset.jpg
preload = /home/zaiquiri/Pictures/Wallpapers/Favorites/The-Great-Wave-Bowl.png
wallpaper = eDP-1, /home/zaiquiri/Pictures/Wallpapers/Favorites/japanese_style_ocean_waves_at_sunset.jpg
wallpaper = HDMI-A-1, /home/zaiquiri/Pictures/Wallpapers/Favorites/The-Great-Wave-Bowl.png
