# See https://wiki.hyprland.org/Configuring/Keywords/ for more

# info at https://wiki.hyprland.org/
source = ~/.config/hypr/hyprconfigs/variables.conf
source = ~/.config/hypr/hyprconfigs/launchers.conf
source = ~/.config/hypr/hyprconfigs/startup.conf
source = ~/.config/hypr/hyprconfigs/monitors.conf
source = ~/.config/hypr/hyprconfigs/windowRules.conf
source = ~/.config/hypr/hyprconfigs/navigation.conf
source = ~/.config/hypr/hyprconfigs/theme.conf
source = ~/.config/hypr/hyprconfigs/keybindings.conf
source = ~/.config/hypr/hyprconfigs/settings.conf

