
# █▀▄▀█ █▀█ █▄░█ █ ▀█▀ █▀█ █▀█ █▀
# █░▀░█ █▄█ █░▀█ █ ░█░ █▄█ █▀▄ ▄█

# See https://wiki.hyprland.org/Configuring/Monitors/


monitor = HDMI-A-6, preferred, 0x0, 1
monitor = DP-6, highrr, 1920x0, 1

# # Auto catch all
# monitor=,preferred,auto,auto

# # Rotaion
# # 0 -> normal (no transforms)
# # 1 -> 90 degrees
# # 2 -> 180 degrees
# # 3 -> 270 degrees
# # 4 -> flipped
# # 5 -> flipped + 90 degrees
# # 6 -> flipped + 180 degrees
# # 7 -> flipped + 270 degrees
