# -----------------------------------------------------
# Keyboard Layout
# https://wiki.hyprland.org/Configuring/Variables/#input
# -----------------------------------------------------
input {
    kb_layout = us,fr
    numlock_by_default = true
    mouse_refocus = false

    # For United States
    # kb_layout = us
    # kb_variant = intl
    # kb_model = pc105
    # kb_options =

    follow_mouse = true
    touchpad {
        # for desktop
        # natural_scroll = false

        # for laptop
        natural_scroll = yes
        # middle_button_emulation = true
        # clickfinger_behavior = false
        drag_lock = true
        scroll_factor = 1.0  # Touchpad scroll factor
    }
    sensitivity = 0 # Pointer speed: -1.0 - 1.0, 0 means no modification.
}

