-- return {
--   "jackMort/ChatGPT.nvim",
--   event = "VeryLazy",
--   config = function()
--     require("chatgpt").setup({
--       api_key_cmd = "pass show chatgptapi",
--     })
--   end,
--   dependencies = {
--     "MunifTanjim/nui.nvim",
--     "nvim-lua/plenary.nvim",
--     "folke/trouble.nvim", -- optional
--     "nvim-telescope/telescope.nvim",
--   },
-- }
